library(argparse)
library(data.table)
library(dplyr)
library(stringr)
library(tidyr)
library(ggplot2)


################################
# Process command line arguments
################################
parser <- ArgumentParser(description="Plot expected versus observed relative abundance (mapped basepairs)")
parser$add_argument('-i', metavar='--input', type='character', 
                    help="Input file: KMA summary .tsv file, generated by Aggregate_by_OTU.R, with reference community data")
parser$add_argument('-r', metavar='--reference_community', type='character', default="",
                    help=" Filepath to a reference community ;-separated csv, containing: Organism; Perc_gDNA")
parser$add_argument('-c', metavar='--category', type='character', default="Experiment",
                    help="Experiment category to compare, should be an experiment-level variable")
args <- parser$parse_args()

KMA <- fread(args$i, sep = "\t", integer64 = "numeric")
Compare_category <- args$c
reference <- args$r

################################
# reference community data
################################
ref_community <- read.csv(reference, sep = ";", dec = ",")
ref_community_name <- str_extract(reference, "/\\w+.csv")
ref_community_name <- str_remove_all(ref_community_name, "/|.csv")
ref_community <- ref_community %>%
  arrange(desc(Perc_gDNA), Organism)

# sort by descending zymo GMS gDNA% -> make organisms into ordered factors
ref_community$Organism <- factor(ref_community$Organism, levels = ref_community$Organism,
                          ordered = TRUE)


################################
# Process combined KMA output data
################################
clean_org_name <- function(organism){
  organism <- str_remove_all(organism, "Synthetic|\\[|\\]|\\scf.")
  organism <- str_replace_all(organism, "_", " ")
  organism <- str_replace_all(organism, "E.coli.*", "Escherichia coli")
  organism <- str_replace_all(organism, "veillonella", "Veillonella")
  organism <- str_replace_all(organism, "\\.", " ")
  organism <- str_extract(organism, "[:upper:]{1}[:lower:]+\\s[:alpha:]+\\.?")
  organism <- str_replace(organism, "Clostridium difficil+e", "Clostridioides difficile")
  return(organism)
}

KMA$taxa <- clean_org_name(KMA$`# refSequence`)
KMA <- KMA %>% 
group_by(Experiment) %>%
  mutate(Total_bp = sum(bpTotal, na.rm = TRUE),
         Total_readCount = sum(readCount, na.rm = TRUE)) %>%
  group_by(taxa, Experiment) %>%
  summarize(p_bpTotal = sum(bpTotal, na.rm = TRUE)/unique(Total_bp),
            mean_queryID = weighted.mean(Query_Identity, bpTotal, na.rm=TRUE),
            mean_query_coverage = weighted.mean(Query_Coverage, bpTotal, na.rm=TRUE),
            mean_templateID = weighted.mean(Template_Identity, bpTotal, na.rm=TRUE),
            total_template_length = sum(Template_length, na.rm=TRUE),
            mean_template_length = mean(Template_length, na.rm=TRUE),
            mean_template_coverage = weighted.mean(Template_Coverage, bpTotal, na.rm=TRUE),
            bpTotal = sum(bpTotal, na.rm = TRUE),
            depth = bpTotal/mean_template_length,
            p_readCount = sum(readCount, na.rm = TRUE)/unique(Total_readCount),
            readCount = sum(readCount, na.rm=TRUE),
            mean_readlength = bpTotal/readCount,
            refConsensusSum = sum(refConsensusSum),
            .groups = "drop")
KMA <- merge(KMA, ref_community, by.x="taxa", by.y = "Organism", all = TRUE)

# heatmap clustering different experimental parameters
heatmap_exp_v_obs <- function(df, categorical){
  # df: data, needs to include a Perc_gDNA var, with expected abundances
  # x: Categorical to be compared (e.g. experimental parameter)
  # ref category: organisms in spike-in community and their expected abundances
  
  df <- df %>%
    filter(p_bpTotal > 0) %>%
    mutate(xaxis = {{categorical}}) %>% 
    filter(!is.na(Perc_gDNA)) %>%
    arrange(desc(Perc_gDNA)) %>%
    mutate(norm_abundance=log2(100*p_bpTotal/Perc_gDNA))
  df$taxa_ab <- paste0(df$taxa, " - ", signif(df$Perc_gDNA, digits = 2), "%")
  df$taxa_ab <- ordered(df$taxa_ab, levels=unique(df$taxa_ab))
  
  # make matrix to cluster categorical
  cl <- df %>%
    select(taxa_ab, norm_abundance, xaxis) %>%
    pivot_wider(names_from = xaxis, values_from = norm_abundance, values_fill = 0)
  clmatrix <- as.matrix(cl[2:ncol(cl)])
  rownames(clmatrix) <- cl$taxa_ab
  clmatrix <- t(clmatrix)
  
  # hierarchical clustering of categorical
  ord <- hclust(dist(clmatrix))$order
  ord_exper <- rownames(clmatrix)[ord]
  # order the experiments
  df$xaxis <- ordered(df$xaxis, levels = ord_exper)
  
  heatmap <- df %>%
    ggplot(aes(x=xaxis, y=taxa_ab)) +
    geom_tile(aes(fill=norm_abundance)) +
    scale_fill_gradient2(name="Log2 of ratio observed/expected",
                         low="blue", mid="#e6e6e6", high="red", midpoint = 0) +
    #reverse organism order on heatmap y axis (i.e. top=high abundance, bottom=low)s
    scale_y_discrete(limits=rev, name=NULL) + 
    scale_x_discrete(position = "top", name=NULL) +
    theme_classic() +
    theme(axis.text.x = element_text(angle=-45, hjust=0.9),
          axis.title.x = element_blank(),
          axis.title.y = element_blank())
  return(heatmap)
}

plot <- heatmap_exp_v_obs(KMA, !!sym(Compare_category))

pdf(NULL)
exportpath <- str_replace(args$i, "\\.tsv?", "_heatmap_exp_v_obs.png")
print(exportpath)
print(plot)
ggsave(exportpath, width = 16, height = 9, dpi = 100)

